language: python
python:
    - "3.6"

branches:
  only:
    - "master"

install:
    - pip install -r requirements-dev.txt

before_script:
    - docker run -d -p 6379:6379 redis:latest

script:
    - tox -e test

after_success:
    coveralls
