language: python
python:
    - "3.6"

install:
    - pip install -r requirements-dev.txt

before_script:
    - docker run -d -p 6379:6379 redis:latest
    - celery -A run.celery worker --detach

script:
    - tox -e test

after_success:
    - coveralls
